apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: efs-sc
  volumeName: {{ .Values.volumename }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.size }}
